<?php

namespace Database\Seeders;

use App\Models\Metric;
use Illuminate\Database\Seeder;

class MetricsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $metrics = array(
            array("name" => "Bag"),
            array("name" => "Box"),
            array("name" => "Pieces"),
            array("name" => "Parts"),
            array("name" => "Kg"),
            array("name" => "20' Container"),
            array("name" => "40' Container"),
            array("name" => "40' HQ Container"),
            array("name" => "Ampere/Amperes"),
            array("name" => "Bags"),
            array("name" => "Barrel/Barrels"),
            array("name" => "Boxes"),
            array("name" => "Bushel/Bushels"),
            array("name" => "Carat/Carats"),
            array("name" => "Carton/Cartons"),
            array("name" => "Case/Cases"),
            array("name" => "Centimeter/Centimeters"),
            array("name" => "Chain/Chains"),
            array("name" => "Cubic Centimeter/Cubic Centimeters"),
            array("name" => "Cubic Foot/Cubic Feet"),
            array("name" => "Cubic Inch/Cubic Inches"),
            array("name" => "Cubic Meter/Cubic Meters"),
            array("name" => "Cubic Yard/Cubic Yards"),
            array("name" => "Degrees Celsius"),
            array("name" => "Degrees Fahrenheit"),
            array("name" => "Dozen/Dozens"),
            array("name" => "Dram/Drams"),
            array("name" => "Fluid Ounce/Fluid Ounces"),
            array("name" => "Foot"),
            array("name" => "Furlong/Furlongs"),
            array("name" => "Gallon/Gallons"),
            array("name" => "Gill/Gills"),
            array("name" => "Grain/Grains"),
            array("name" => "Gram/Grams"),
            array("name" => "Gross"),
            array("name" => "Hertz"),
            array("name" => "Inch/Inches"),
            array("name" => "Kilogram/Kilograms"),
            array("name" => "Kilowatt/Kilowatts"),
            array("name" => "Liter/Liters"),
            array("name" => "Long Ton/Long Tons"),
            array("name" => "Megahertz"),
            array("name" => "Metric Ton/Metric Tons"),
            array("name" => "Milliliter/Milliliters"),
            array("name" => "Millimeter/Millimeters"),
            array("name" => "Ounce/Ounces"),
            array("name" => "Pack/Packs"),
            array("name" => "Pairs"),
            array("name" => "Pallet/Pallets"),
            array("name" => "Parcel/Parcels"),
            array("name" => "Perch/Perches"),
            array("name" => "Pieces"),
            array("name" => "Pint/Pints"),
            array("name" => "Plant/Plants"),
            array("name" => "Pole/Poles"),
            array("name" => "Pound/Pounds"),
            array("name" => "Quart/Quarts"),
            array("name" => "Quarter/Quarters"),
            array("name" => "Reams"),
            array("name" => "Rod/Rods"),
            array("name" => "Rolls"),
            array("name" => "Sets"),
            array("name" => "Sheet/Sheets"),
            array("name" => "Short Ton/Short Tons"),
            array("name" => "Square Centimeter/Square Centimeters"),
            array("name" => "Square Feet"),
            array("name" => "Square Inch/Square Inches"),
            array("name" => "Square Meters"),
            array("name" => "Square Mile/Square Miles"),
            array("name" => "Square Yard/Square Yards"),
            array("name" => "Stone/Stones"),
            array("name" => "Strand/Strands"),
            array("name" => "Tonne/Tonnes"),
            array("name" => "Tons"),
            array("name" => "Tray/Trays"),
            array("name" => "Unit/Units"),
            array("name" => "Yard/Yards"),
            array("name" => "Bag"),
            array("name" => "Box"),
            array("name" => "Pieces"),
            array("name" => "Parts"),
            array("name" => "Kg"),
            array("name" => "20' Container"),
            array("name" => "40' Container"),
            array("name" => "40' HQ Container"),
            array("name" => "Ampere/Amperes"),
            array("name" => "Bags"),
            array("name" => "Barrel/Barrels"),
            array("name" => "Boxes"),
            array("name" => "Bushel/Bushels"),
            array("name" => "Carat/Carats"),
            array("name" => "Carton/Cartons"),
            array("name" => "Case/Cases"),
            array("name" => "Centimeter/Centimeters"),
            array("name" => "Chain/Chains"),
            array("name" => "Cubic Centimeter/Cubic Centimeters"),
            array("name" => "Cubic Foot/Cubic Feet"),
            array("name" => "Cubic Inch/Cubic Inches"),
            array("name" => "Cubic Meter/Cubic Meters"),
            array("name" => "Cubic Yard/Cubic Yards"),
            array("name" => "Degrees Celsius"),
            array("name" => "Degrees Fahrenheit"),
            array("name" => "Dozen/Dozens"),
            array("name" => "Dram/Drams"),
            array("name" => "Fluid Ounce/Fluid Ounces"),
            array("name" => "Foot"),
            array("name" => "Furlong/Furlongs"),
            array("name" => "Gallon/Gallons"),
            array("name" => "Gill/Gills"),
            array("name" => "Grain/Grains"),
            array("name" => "Gram/Grams"),
            array("name" => "Gross"),
            array("name" => "Hertz"),
            array("name" => "Inch/Inches"),
            array("name" => "Kilogram/Kilograms"),
            array("name" => "Kilowatt/Kilowatts"),
            array("name" => "Liter/Liters"),
            array("name" => "Long Ton/Long Tons"),
            array("name" => "Megahertz"),
            array("name" => "Metric Ton/Metric Tons"),
            array("name" => "Milliliter/Milliliters"),
            array("name" => "Millimeter/Millimeters"),
            array("name" => "Ounce/Ounces"),
            array("name" => "Pack/Packs"),
            array("name" => "Pairs"),
            array("name" => "Pallet/Pallets"),
            array("name" => "Parcel/Parcels"),
            array("name" => "Perch/Perches"),
            array("name" => "Pieces"),
            array("name" => "Pint/Pints"),
            array("name" => "Plant/Plants"),
            array("name" => "Pole/Poles"),
            array("name" => "Pound/Pounds"),
            array("name" => "Quart/Quarts"),
            array("name" => "Quarter/Quarters"),
            array("name" => "Reams"),
            array("name" => "Rod/Rods"),
            array("name" => "Rolls"),
            array("name" => "Sets"),
            array("name" => "Sheet/Sheets"),
            array("name" => "Short Ton/Short Tons"),
            array("name" => "Square Centimeter/Square Centimeters"),
            array("name" => "Square Feet"),
            array("name" => "Square Inch/Square Inches"),
            array("name" => "Square Meters"),
            array("name" => "Square Mile/Square Miles"),
            array("name" => "Square Yard/Square Yards"),
            array("name" => "Stone/Stones"),
            array("name" => "Strand/Strands"),
            array("name" => "Tonne/Tonnes"),
            array("name" => "Tons"),
            array("name" => "Tray/Trays"),
            array("name" => "Unit/Units"),
            array("name" => "Yard/Yards"),
            array("name" => "Color"),
            array("name" => "Set"),
            array("name" => "RFQ"),
            array("name" => "Test"),
            array("name" => "DFLTM"),
        );
        foreach ($metrics as $metric) {
            Metric::create($metric);
        }
    }
}
