version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/searchmeetings
hooks:
  BeforeInstall:
    - location: deploy/scripts/beforeInstall.sh
      timeout: 600
  AfterInstall:
    - location: deploy/scripts/afterInstall.sh
      timeout: 300
      runas: ubuntu 
  